project_name: keruta-agent

builds:
  - main: ./cmd/keruta-agent
    binary: keruta-agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

signs:
  - artifacts: checksum
    args: ["--armor", "--detach-sign"]

dockers: [] 