# keruta-agent バイナリリリース設定
# この設定は実行バイナリのみをリリースします
project_name: keruta-agent

builds:
  - main: ./cmd/keruta-agent
    binary: keruta-agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# アーカイブを作成せず、バイナリのみをリリースに添付する
archives:
  - format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

# Dockerイメージは作成しない（バイナリのみ）
dockers: [] 