name: Auto Tag Latest Version

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    name: Create and Push Latest Version Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # Get the latest tag, or set v0.0.0 if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          # Extract version components
          LATEST_TAG=${{ steps.get_latest_tag.outputs.latest_tag }}
          
          # Remove 'v' prefix
          VERSION=${LATEST_TAG#v}
          
          # Split into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Increment patch version
          PATCH=$((PATCH + 1))
          
          # Create new version
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $NEW_VERSION -m "Release $NEW_VERSION"
          git push origin $NEW_VERSION