name: Release Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up QEMU (for cross-build)
        uses: docker/setup-qemu-action@v3

      - name: Build and Release Binary
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

# GoReleaser設定ファイル (.goreleaser.yml) でバイナリビルドのみが設定されています
# このワークフローは実行バイナリのみをリリースします 